export const FETCH_AUTOCOMPLETES_REQUEST = "FETCH_AUTOCOMPLETES_REQUEST";
export const FETCH_AUTOCOMPLETES_SUCCESS = "FETCH_AUTOCOMPLETES_SUCCESS";
export const FETCH_AUTOCOMPLETES_FAILED = "FETCH_AUTOCOMPLETES_FAILED";

export const getAutocompletes = (payload) => ({
  type: FETCH_AUTOCOMPLETES_REQUEST,
  payload,
});
